set t_Co=256
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'
Plug 'editorconfig/editorconfig-vim' " editorconfig, always not fucking working
Plug 'tpope/vim-commentary' " allows typing v-select block then gc to comment block
Plug 'tpope/vim-fugitive' " allows some git commands inside vim
Plug 'joshdick/onedark.vim' " theme
Plug 'altercation/vim-colors-solarized'
Plug 'vim-airline/vim-airline' " status line
Plug 'scrooloose/nerdtree'
Plug 'w0rp/ale' " autofix and linting
Plug 'Xuyuanp/nerdtree-git-plugin' " display files as modified from git in nerdtree
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'yegappan/mru'
Plug 'lifepillar/vim-mucomplete'
Plug 'Quramy/tsuquyomi'
Plug 'leafgarland/typescript-vim'
call plug#end()
colorscheme onedark
let g:airline#extensions#tabline#enabled = 1
"closes nerdtree on last
set mouse=a
set autoread
set nu
set noswapfile
set nobackup
set nowb

let NERDTreeMouseMode=3
let g:ale_fixers = ['eslint']
let g:ale_fix_on_save = 1

set list

" quit if nerdtree is last window
autocmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
autocmd BufEnter * if &modifiable && winwidth('%')>100 && &filetype !=# 'gitcommit' | NERDTreeFind | wincmd p | endif

autocmd VimEnter * if winwidth('%')>100 && &filetype !=# 'gitcommit' | NERDTree | wincmd p | endif



"
nnoremap  <C-F> :Rg<ENTER>
nnoremap  <C-G> :GFiles<ENTER>
set completeopt+=menuone
set completeopt+=noselect
set shortmess+=c   " Shut off completion messages
set belloff+=ctrlg " If Vim beeps during completion
let g:mucomplete#enable_auto_at_startup = 1



set ignorecase
set smartcase
set backspace=indent,eol,start

