
[[ -z "$TMUX" ]] && exec tmux -2
[[ $- != *i* ]] && return


export EDITOR="vim"
alias stp="git subtree push --prefix dist origin gh-pages"
alias e="vim"
alias g="git status -uno"
alias y="yarn"
alias w="curl wttr.in"
alias tk="tmux kill-server"
alias ag="rg"
alias ls="exa"
alias ll="exa -l"
alias lt="exa -lsnew"
alias ff="fd|grep"
alias sau="sudo apt update&&sudo apt upgrade"
alias cov="yarn test --coverage && opn coverage/lcov-report/index.html"
alias ydl="youtube-dl"
alias yda="youtube-dl -f 'bestaudio[ext=m4a]' "
alias grep="grep --color=never"
alias unarx="parallel unar {} ::: ~/Downloads/*.7z(.N) ~/Downloads/*.rar(.N) ~/Downloads/*.zip(.N)"
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias pserver='python -m RangeHTTPServer'
alias smaller="parallel convert -resize 50% {} resized.{} ::: *.jpg"

debug () {
  node --inspect-brk node_modules/.bin/jest $@
  opn chrome://inspect
}


# check for dead links on a given wikipedia URL, excluding some stuff that tends to be always alive are not receptive to bot hits


#http://seqanswers.com/forums/showthread.php?t=23166
function sortblast {
    sort -k1,1 -k12,12gr -k11,11g -k3,3gr $1 | sort -u -k1,1 --merge > $2
}


export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000

PATH="/home/cdiesh/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/cdiesh/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/cdiesh/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/cdiesh/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/cdiesh/perl5"; export PERL_MM_OPT;


bindkey "^P" history-beginning-search-backward
bindkey "^N" history-beginning-search-forward


export PATH=$PATH:~/go/bin:~/bin
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source /home/linuxbrew/.linuxbrew/Cellar/z/1.9/etc/profile.d/z.sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
nvm use system
