
[[ -z "$TMUX" ]] && exec tmux -2
[[ $- != *i* ]] && return


export EDITOR="vim"
alias stp="git subtree push --prefix dist origin gh-pages"
alias e="vim"
alias pserver="python -m RangeHTTPServer"
alias unrarx="parallel unrar x {} ~/Music ::: *.rar"
alias ll="ls -l"
alias ydl="youtube-dl" # quick download youtube
alias yda="youtube-dl -f 'bestaudio[ext=m4a]'" # quick download audio
alias smaller="parallel convert -resize 50% {} resized.{} ::: *.jpg" # resize all files to 50% in pictures
alias sau="sudo apt update && sudo apt upgrade" # quick upgrade
alias ff="/usr/bin/ag -g" # find file
alias pbcopy="xsel --clipboard --input" # mirror of osx pbcopy on linux
alias pbpaste="xsel --clipboard --output" # mirror of osx pbpaste on linux
alias cov="yarn test --coverage && opn coverage/lcov-report/index.html" # quickly open up coverage report
alias gd="git diff --relative" # use relative paths for git diff
alias w="curl wttr.in"

# make ag actually use git grep and ignore snap files
ag () {
  local port="${2:-./*}"
  git grep -i $1 -- $port ':(exclude)*.snap'
}


export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000

PATH="/home/cdiesh/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/cdiesh/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/cdiesh/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/cdiesh/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/cdiesh/perl5"; export PERL_MM_OPT;



bindkey "^P" history-beginning-search-backward
bindkey "^N" history-beginning-search-forward


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:~/go/bin:~/bin
