set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -sg escape-time 10
set -g focus-events on
set -g set-clipboard on
set -g history-limit 50000
set -g mouse on
set -g prefix C-]
set -g status-right '#(date +%Y-%m-%d)'
set -g status-interval 5000
set -g status-style bg=default

setw -g mode-keys vi
unbind -T copy-mode-vi Enter
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

bind = split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind -n M-Left previous-window
bind -n M-Right next-window

source-file -q ~/.tmux.conf.local
